name: Build Storybook

on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci

      - name: Build Storybook
        run: npm run build-storybook

      - name: Deploy to Chromatic
        run: npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }} --exit-zero-on-changes
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

      - name: Notify Discord
        run: |
          curl -H "Content-Type: application/json" \
            -d "{\"content\":\"🎉 Storybook 배포 완료! 👉 https://www.chromatic.com/builds?appId=67fd2a40cad99feac1d5563d\"}" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}